'use client';

import React, { useState, useEffect, useRef } from 'react';
import { FZ } from './fedor-visual-lab-engine';

interface LaboratorioVisualModal4toProps {
  isOpen: boolean;
  onClose: () => void;
}

interface LabTool {
  id: string;
  icon: string;
  name: string;
  color: string;
  labels: string[];
  defaults: (string | number)[];
  genText: (v: (string | number)[]) => string;
}

const LAB_TOOLS: LabTool[] = [
  // Fila 1
  {
    id: 'sumar',
    icon: '➕',
    name: 'Sumar',
    color: '#5C21A6',
    labels: ['a', 'b'],
    defaults: [47, 35],
    genText: (v) => `${v[0]} + ${v[1]} = ?`,
  },
  {
    id: 'restar',
    icon: '➖',
    name: 'Restar',
    color: '#7C3AED',
    labels: ['a', 'b'],
    defaults: [82, 47],
    genText: (v) => `${v[0]} - ${v[1]} = ?`,
  },
  {
    id: 'multiplicar',
    icon: '✖️',
    name: 'Multiplicar',
    color: '#E8650A',
    labels: ['a', 'b'],
    defaults: [6, 7],
    genText: (v) => `${v[0]} × ${v[1]} = ?`,
  },
  {
    id: 'repartir',
    icon: '🍬',
    name: 'Repartir',
    color: '#16876A',
    labels: ['total', 'entre'],
    defaults: [23, 4],
    genText: (v) => `Se reparten ${v[0]} dulces entre ${v[1]} niños`,
  },
  {
    id: 'fraccion',
    icon: '🍕',
    name: 'Fracción',
    color: '#F59E0B',
    labels: ['arriba', 'abajo'],
    defaults: [6, 8],
    genText: (v) => `Simplifica la fracción ${v[0]}/${v[1]} a su mínima expresión.`,
  },
  {
    id: 'sumar-fracciones',
    icon: '➕',
    name: 'Sumar fracciones',
    color: '#D97706',
    labels: ['a/b', 'c/d'],
    defaults: ['1/2', '1/3'],
    genText: (v) => `${v[0]} + ${v[1]} = ?`,
  },
  // Fila 2
  {
    id: 'divisores',
    icon: '🔍',
    name: 'Divisores',
    color: '#0F766E',
    labels: ['número'],
    defaults: [24],
    genText: (v) => `¿Cuáles son los divisores de ${v[0]}? divisor`,
  },
  {
    id: 'mcd',
    icon: '🔗',
    name: 'MCD',
    color: '#0E7490',
    labels: ['a', 'b'],
    defaults: [12, 18],
    genText: (v) => `¿Cuál es el MCD de ${v[0]} y ${v[1]}?`,
  },
  {
    id: 'mcm',
    icon: '🔁',
    name: 'MCM',
    color: '#0369A1',
    labels: ['a', 'b'],
    defaults: [4, 6],
    genText: (v) => `¿Cuál es el MCM de ${v[0]} y ${v[1]}?`,
  },
  {
    id: 'potencia',
    icon: '⚡',
    name: 'Potencia',
    color: '#7C3AED',
    labels: ['base', 'exp.'],
    defaults: [3, 2],
    genText: (v) => `Calcula: ${v[0]}^${v[1]} = ?`,
  },
  {
    id: 'raiz',
    icon: '√',
    name: 'Raíz',
    color: '#9333EA',
    labels: ['número'],
    defaults: [36],
    genText: (v) => `Calcula: √${v[0]} = ?`,
  },
  {
    id: 'unidades',
    icon: '📏',
    name: 'Unidades',
    color: '#0891B2',
    labels: ['valor', 'de', 'a'],
    defaults: [3, 'm', 'cm'],
    genText: (v) => `¿A cuántos ${v[2]} equivalen ${v[0]} ${v[1]}?`,
  },
  // Fila 3
  {
    id: 'area',
    icon: '🟩',
    name: 'Área',
    color: '#059669',
    labels: ['largo', 'ancho'],
    defaults: [6, 4],
    genText: (v) => `Calcula el área (en m²) de un rectángulo de ${v[0]} m × ${v[1]} m.`,
  },
  {
    id: 'volumen',
    icon: '🧊',
    name: 'Volumen',
    color: '#0D9488',
    labels: ['l', 'a', 'h'],
    defaults: [3, 2, 4],
    genText: (v) => `Calcula el volumen (en m³) de un prisma de ${v[0]} m × ${v[1]} m × ${v[2]} m.`,
  },
  {
    id: 'porcentaje',
    icon: '％',
    name: 'Porcentaje',
    color: '#BE185D',
    labels: ['%', 'de'],
    defaults: [25, 200],
    genText: (v) => `Halla el ${v[0]} % de ${v[1]}.`,
  },
  {
    id: 'balanza',
    icon: '⚖️',
    name: 'Balanza',
    color: '#3D1468',
    labels: ['x +', '='],
    defaults: [7, 15],
    genText: (v) => `Resuelve la ecuación: x + ${v[0]} = ${v[1]}`,
  },
  {
    id: 'dado',
    icon: '🎲',
    name: 'Dado',
    color: '#B45309',
    labels: [],
    defaults: [],
    genText: () => '¿Cuál es la probabilidad al lanzar un dado de 6 caras?',
  },
  {
    id: 'bolsa',
    icon: '👜',
    name: 'Bolsa',
    color: '#92400E',
    labels: ['rojas', 'total'],
    defaults: [3, 10],
    genText: (v) => `En una bolsa hay ${v[1]} bolas y ${v[0]} son rojas.`,
  },
];

export default function LaboratorioVisualModal4to({ isOpen, onClose }: LaboratorioVisualModal4toProps) {
  const [selectedIdx, setSelectedIdx] = useState(0);
  const [inputs, setInputs] = useState<(string | number)[]>(LAB_TOOLS[0].defaults);
  const [htmlContent, setHtmlContent] = useState('');
  const boardRef = useRef<HTMLDivElement>(null);

  // Expose global helpers on window for inline event handlers generated by FZ
  useEffect(() => {
    if (typeof window !== 'undefined') {
      (window as any).FZ = FZ;

      // Colombian audio narration
      (window as any).fedor5Hablar = (text: string) => {
        try {
          if ('speechSynthesis' in window) {
            window.speechSynthesis.cancel();
            const u = new SpeechSynthesisUtterance(text);
            u.lang = 'es-CO';
            u.rate = 0.95;
            window.speechSynthesis.speak(u);
          }
        } catch {}
      };

      // Sound chime
      (window as any).fedor5Tono = (freq = 520) => {
        try {
          const AudioContextClass = window.AudioContext || (window as any).webkitAudioContext;
          if (AudioContextClass) {
            const ctx = new AudioContextClass();
            const osc = ctx.createOscillator();
            const gain = ctx.createGain();
            osc.connect(gain);
            gain.connect(ctx.destination);
            osc.frequency.value = typeof freq === 'number' ? freq : 520;
            gain.gain.setValueAtTime(0.08, ctx.currentTime);
            gain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.15);
            osc.start();
            osc.stop(ctx.currentTime + 0.15);
          }
        } catch {}
      };
    }
  }, []);

  const renderTool = (toolIndex: number, currentInputs: (string | number)[]) => {
    const tool = LAB_TOOLS[toolIndex];
    if (!tool) return;
    try {
      // Parse inputs: convert numeric strings to number if purely digits
      const parsed = currentInputs.map((val) => {
        const s = String(val).trim();
        return /^\d+$/.test(s) ? Number(s) : s;
      });
      const queryText = tool.genText(parsed);
      const generatedHtml = FZ.crear ? FZ.crear({ q: queryText, ctx: '' }, 'ej') : '';
      setHtmlContent(
        generatedHtml ||
          '<div class="p-6 text-center text-gray-500 font-bold text-sm bg-purple-50 rounded-2xl border border-purple-200">Prueba con otros números (más pequeños)</div>'
      );
    } catch {
      setHtmlContent(
        '<div class="p-6 text-center text-gray-500 font-bold text-sm bg-purple-50 rounded-2xl border border-purple-200">Prueba con otros números</div>'
      );
    }
  };

  // Initial render when modal opens
  useEffect(() => {
    if (isOpen) {
      renderTool(selectedIdx, inputs);
    }
  }, [isOpen]);

  const handleSelectTool = (idx: number) => {
    setSelectedIdx(idx);
    const newDefaults = [...LAB_TOOLS[idx].defaults];
    setInputs(newDefaults);
    renderTool(idx, newDefaults);
    // Sound chime on tool select
    if (typeof window !== 'undefined' && typeof (window as any).fedor5Tono === 'function') {
      (window as any).fedor5Tono();
    }
  };

  const handleGo = () => {
    renderTool(selectedIdx, inputs);
    if (typeof window !== 'undefined' && typeof (window as any).fedor5Tono === 'function') {
      (window as any).fedor5Tono();
    }
  };

  if (!isOpen) return null;

  const currentTool = LAB_TOOLS[selectedIdx];

  return (
    <div className="fixed inset-0 z-[99999] flex items-center justify-center p-3 sm:p-5 bg-black/75 backdrop-blur-sm animate-fadeIn">
      {/* Visual lab styles injected directly */}
      <style>{`
        /* ── Visual Lab Styles ── */
        .fz {
          margin: 12px 0 14px;
          border-radius: 20px;
          background: linear-gradient(160deg, #F8F5FF, #EEF7FF);
          border: 2.5px solid #D9CCFF;
          box-shadow: 0 8px 22px rgba(60, 20, 120, 0.10);
          overflow: hidden;
          font-family: 'Nunito', sans-serif;
          color: #1A1033;
          text-align: left;
        }
        .fz-h {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 8px;
          padding: 10px 16px;
          background: linear-gradient(90deg, var(--fz1, #5C21A6), var(--fz2, #8B3EDB));
          color: #FFFFFF !important;
        }
        .fz-h .t {
          flex: 1;
          font-family: 'Baloo 2', Nunito, sans-serif;
          font-weight: 900;
          font-size: 16px;
          letter-spacing: .01em;
          color: #FFFFFF !important;
          display: flex;
          align-items: center;
          gap: 6px;
        }
        .fz-h .t small {
          font-family: 'Nunito', sans-serif;
          font-weight: 700;
          font-size: 13px;
          opacity: .9;
          color: rgba(255, 255, 255, 0.9) !important;
        }
        .fz-h button {
          background: rgba(255, 255, 255, 0.2);
          border: 1.5px solid rgba(255, 255, 255, 0.45);
          color: #FFFFFF;
          border-radius: 10px;
          padding: 4px 10px;
          font-weight: 900;
          cursor: pointer;
          font-family: 'Nunito', sans-serif;
          font-size: 14px;
        }
        .fz-b {
          padding: 16px 12px;
          overflow-x: auto;
        }
        .fz.min .fz-b, .fz.min .fz-f {
          display: none;
        }
        .fz-f {
          display: flex;
          flex-wrap: wrap;
          gap: 8px;
          padding: 0 16px 16px;
          align-items: center;
        }
        .fz-btn {
          border: none;
          border-radius: 14px;
          padding: 9px 16px;
          font-weight: 900;
          font-size: 13px;
          cursor: pointer;
          font-family: 'Nunito', sans-serif;
          color: #FFFFFF;
          background: linear-gradient(135deg, #5C21A6, #8B3EDB);
          box-shadow: 0 3px 10px rgba(92, 33, 166, 0.3);
          transition: transform .12s, filter .12s;
        }
        .fz-btn:hover {
          transform: translateY(-2px);
          filter: brightness(1.08);
        }
        .fz-btn.o { background: linear-gradient(135deg, #FF8C2A, #E8650A); }
        .fz-btn.g { background: linear-gradient(135deg, #16876A, #24C496); }
        .fz-btn.b { background: linear-gradient(135deg, #0E6BA8, #38BDF8); }
        .fz-btn.w {
          background: #FFFFFF;
          color: #5C21A6 !important;
          border: 2px solid #C5BFEE;
          box-shadow: none;
        }
        .fz-btn.on { outline: 3px solid #FFE066; }
        .fz-msg {
          font-weight: 900;
          font-size: 13.5px;
          color: #3D1468;
          padding: 7px 14px;
          background: #FFFFFF;
          border-radius: 14px;
          border: 2px dashed #C5BFEE;
          min-height: 20px;
          display: inline-flex;
          align-items: center;
        }
        .fz-tip {
          font-size: 12.5px;
          font-weight: 800;
          color: #6B5E8A;
          margin-top: 10px;
          text-align: center;
        }
        /* Pizarra en columnas */
        .fz-col {
          border-collapse: separate;
          border-spacing: 6px;
          margin: 0 auto;
        }
        .fz-col th {
          font-size: 13px;
          font-weight: 900;
          color: #FFFFFF;
          border-radius: 9px;
          padding: 4px 8px;
          width: 48px;
          min-width: 44px;
          text-align: center;
        }
        .fz-col td {
          width: 48px;
          height: 48px;
          text-align: center;
          font-family: 'Baloo 2', sans-serif;
          font-size: 26px;
          font-weight: 900;
          color: #1A1033;
          border-radius: 12px;
          background: #FFFFFF;
          border: 2px solid #EEE8FB;
          box-shadow: 0 2px 5px rgba(0,0,0,0.04);
        }
        .fz-col td.op {
          background: transparent;
          border: none;
          color: #E8650A;
          box-shadow: none;
          font-size: 28px;
        }
        .fz-col td.nb { background: transparent; border: none; box-shadow: none; }
        .fz-col td.cm { width: 14px; background: transparent; border: none; font-size: 30px; color: #C94B22; box-shadow: none; }
        .fz-col tr.cr td {
          height: 30px;
          font-size: 16px;
          background: transparent;
          border: none;
          box-shadow: none;
        }
        .fz-col input {
          width: 100%;
          height: 100%;
          border: none;
          background: transparent;
          text-align: center;
          font-family: 'Baloo 2', sans-serif;
          font-size: 26px;
          font-weight: 900;
          color: #16876A;
          outline: none;
        }
        .fz-col tr.cr input {
          font-size: 16px;
          color: #C94B22;
          font-weight: 900;
        }
        .fz-col tr.rs td {
          background: #FFFBEA;
          border: 2.5px dashed #F5C518;
        }
        .fz-col tr.rs td.op, .fz-col tr.rs td.cm { background: transparent; border: none; box-shadow: none; }
        .fz-col tr.ln td {
          height: 4px;
          background: #1A1033;
          border: none;
          border-radius: 2px;
          padding: 0;
          box-shadow: none;
        }
        .fz-col td.hl {
          background: #FFE066 !important;
          transform: scale(1.08);
          transition: all .2s;
        }
        /* Bloques base 10 */
        .fz-blk { display: flex; flex-wrap: wrap; gap: 14px; justify-content: center; align-items: flex-end; }
        .fz-blk .g { display: flex; flex-direction: column; align-items: center; gap: 4px; }
        .fz-blk .row { display: flex; gap: 3px; align-items: flex-end; flex-wrap: wrap; max-width: 260px; justify-content: center; }
        .fz-blk .lab { font-weight: 900; font-size: 13px; color: #3D1468; }
        .fz-c100 { width: 40px; height: 40px; background: repeating-linear-gradient(0deg,#1A6CB4 0 3.6px,#4DA6FF 3.6px 4px),#4DA6FF; border: 1.5px solid #0A3D6E; border-radius: 3px; }
        .fz-c10 { width: 6px; height: 40px; background: repeating-linear-gradient(0deg,#16876A 0 3.6px,#6EE7B7 3.6px 4px); border: 1px solid #074F3A; border-radius: 2px; }
        .fz-c1 { width: 7px; height: 7px; background: #FF8C2A; border: 1px solid #7A3200; border-radius: 2px; }
        /* Puntos y Arreglos */
        .fz-dots { display: inline-grid; gap: 5px; padding: 8px; background: #FFFFFF; border-radius: 14px; border: 2px solid #EEE8FB; }
        .fz-dot { width: 18px; height: 18px; border-radius: 50%; background: radial-gradient(circle at 35% 30%,#FFD27A,#E8650A); box-shadow: 0 1px 3px rgba(0,0,0,.25); transition: all .25s; }
        .fz-dot.off { background: #E8DBFF; box-shadow: none; }
        .fz-dot.rest { background: radial-gradient(circle at 35% 30%,#FF9AA2,#C94B22); }
        .fz-dot.sel { background: radial-gradient(circle at 35% 30%,#8EF0C9,#16876A); }
        /* Reparto */
        .fz-plates { display: flex; flex-wrap: wrap; gap: 8px; justify-content: center; }
        .fz-plate { min-width: 74px; min-height: 74px; border-radius: 50%; background: radial-gradient(circle,#FFFFFF 55%,#EDE3FF 56%); border: 3px solid #C5BFEE; display: flex; flex-wrap: wrap; align-content: center; justify-content: center; gap: 2px; padding: 10px; position: relative; }
        .fz-plate b { position: absolute; bottom: -8px; left: 50%; transform: translateX(-50%); background: #5C21A6; color: #fff; border-radius: 8px; font-size: 11px; padding: 0 6px; }
        .fz-pile { display: flex; flex-wrap: wrap; gap: 3px; justify-content: center; padding: 8px; background: #FFF6E0; border-radius: 14px; border: 2px dashed #F5C518; margin-bottom: 10px; min-height: 30px; }
        .fz-cand { font-size: 18px; line-height: 1; animation: fzPop .3s ease; }
        @keyframes fzPop { from { transform: scale(0); } to { transform: scale(1); } }
        /* Fracciones */
        .fz-frow { display: flex; flex-wrap: wrap; gap: 16px; align-items: center; justify-content: center; }
        .fz-bar { display: flex; height: 44px; border-radius: 10px; overflow: hidden; border: 2.5px solid #3D1468; background: #FFFFFF; min-width: 160px; max-width: 100%; }
        .fz-bar i { flex: 1; border-right: 2px solid #3D1468; cursor: pointer; transition: background .2s; }
        .fz-bar i:last-child { border-right: none; }
        .fz-bar i.on { background: linear-gradient(180deg,#FFB547,#FF8C2A); }
        .fz-bar i.on2 { background: linear-gradient(180deg,#6EE7B7,#16876A); }
        .fz-bar i.gb { border-right-width: 5px; }
        .fz-fr { display: inline-flex; flex-direction: column; align-items: center; font-family: "Baloo 2", sans-serif; font-weight: 900; font-size: 24px; line-height: 1; color: #3D1468; }
        .fz-fr span:first-child { border-bottom: 3px solid #3D1468; padding: 0 6px; }
        /* Grilla 10x10 */
        .fz-g100 { display: inline-grid; grid-template-columns: repeat(10,22px); gap: 2px; padding: 6px; background: #3D1468; border-radius: 10px; }
        .fz-g100 i { width: 22px; height: 22px; background: #FFFFFF; border-radius: 3px; cursor: pointer; transition: background .15s; }
        .fz-g100 i.on { background: linear-gradient(135deg,#FFB547,#FF8C2A); }
        /* Chips */
        .fz-chips { display: flex; flex-wrap: wrap; gap: 5px; align-items: center; }
        .fz-chip { min-width: 34px; padding: 5px 9px; border-radius: 12px; background: #FFFFFF; border: 2px solid #D9CCFF; font-weight: 900; font-size: 14px; text-align: center; cursor: pointer; transition: all .15s; }
        .fz-chip.on { background: #FFE066; border-color: #F5A524; transform: scale(1.08); }
        .fz-chip.cm { background: #6EE7B7; border-color: #16876A; }
        .fz-rowlab { font-family: "Baloo 2", sans-serif; font-weight: 900; font-size: 16px; color: #5C21A6; min-width: 88px; }
        /* Tablero de valor posicional */
        .fz-pv { display: flex; gap: 4px; justify-content: center; flex-wrap: wrap; }
        .fz-pv .c { display: flex; flex-direction: column; align-items: center; gap: 4px; cursor: pointer; }
        .fz-pv .c .h { font-size: 11px; font-weight: 900; color: #fff; border-radius: 8px; padding: 3px 6px; min-width: 46px; text-align: center; }
        .fz-pv .c .d { width: 48px; height: 56px; border-radius: 12px; background: #FFFFFF; border: 2.5px solid #D9CCFF; display: flex; align-items: center; justify-content: center; font-family: "Baloo 2", sans-serif; font-size: 32px; font-weight: 900; }
        .fz-pv .c.on .d { background: #FFE066; border-color: #F5A524; transform: translateY(-4px); }
        .fz-pv .cm { font-size: 40px; font-weight: 900; color: #C94B22; align-self: flex-end; margin-bottom: 6px; }
        /* Balanza y Recta SVG */
        .fz-eq { font-family: "Baloo 2", sans-serif; font-size: 24px; font-weight: 900; text-align: center; color: #3D1468; margin-top: 4px; }
        .fz-svg { display: block; margin: 0 auto; max-width: 100%; height: auto; }
      `}</style>

      {/* Main Modal Card */}
      <div
        className="w-full max-w-4xl bg-white rounded-3xl p-5 sm:p-7 shadow-2xl relative flex flex-col max-h-[92vh] overflow-hidden"
        style={{ fontFamily: "'Nunito', sans-serif" }}
      >
        {/* Header Modal */}
        <div className="flex items-center justify-between pb-3 mb-3 border-b border-purple-100">
          <h2
            className="text-2xl font-black text-[#5C21A6] flex items-center gap-2"
            style={{ fontFamily: "'Baloo 2', sans-serif" }}
          >
            <span>🧠</span>
            <span>Laboratorio visual</span>
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="Cerrar modal"
            className="w-10 h-10 rounded-full bg-[#F3EEFF] hover:bg-[#E9DEFF] text-[#5C21A6] font-black text-xl flex items-center justify-center transition-colors cursor-pointer"
          >
            ✕
          </button>
        </div>

        {/* Scrollable Modal Content */}
        <div className="overflow-y-auto pr-1 space-y-4 flex-1">
          {/* Banner Hero */}
          <div
            className="rounded-2xl p-4 sm:p-5 text-white shadow-md relative overflow-hidden"
            style={{
              background: 'linear-gradient(135deg, #BE185D 0%, #7C3AED 55%, #0E6BA8 100%)',
            }}
          >
            <h3
              className="text-xl sm:text-2xl font-black mb-1 flex items-center gap-2"
              style={{ fontFamily: "'Baloo 2', sans-serif" }}
            >
              <span>🧠</span>
              <span>Laboratorio visual</span>
            </h3>
            <p className="text-xs sm:text-sm font-semibold text-white/95">
              Elige una herramienta, cambia los números y experimenta. ¡Aquí puedes jugar sin límite!
            </p>
          </div>

          {/* 18 Tools Grid (3 rows x 6 columns) */}
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 sm:gap-2.5">
            {LAB_TOOLS.map((tool, idx) => {
              const isSelected = selectedIdx === idx;
              return (
                <button
                  key={tool.id}
                  type="button"
                  onClick={() => handleSelectTool(idx)}
                  className={`h-[78px] rounded-2xl text-center text-white font-black cursor-pointer transition-all flex flex-col items-center justify-center gap-1 shadow-md hover:scale-[1.03] active:scale-95 ${
                    isSelected
                      ? 'ring-4 ring-yellow-400 ring-offset-2 scale-105 shadow-xl z-10'
                      : 'opacity-95 hover:opacity-100'
                  }`}
                  style={{
                    background: `linear-gradient(145deg, ${tool.color}, ${tool.color}E6)`,
                  }}
                >
                  <span className="text-2xl sm:text-3xl leading-none">{tool.icon}</span>
                  <span className="text-xs sm:text-[13px] font-black leading-tight truncate px-1">
                    {tool.name}
                  </span>
                </button>
              );
            })}
          </div>

          {/* Input Control Row */}
          <div className="flex items-center justify-center gap-3.5 my-3 flex-wrap">
            <b
              className="font-black text-lg sm:text-xl text-[#3D1468] flex items-center gap-1.5"
              style={{ fontFamily: "'Baloo 2', sans-serif" }}
            >
              <span>{currentTool.icon}</span>
              <span>{currentTool.name}:</span>
            </b>

            {currentTool.labels.map((lbl, k) => (
              <label
                key={k}
                className="flex flex-col items-center text-xs font-black text-[#6B5E8A] gap-1"
              >
                <span>{lbl}</span>
                <input
                  type="text"
                  value={inputs[k] ?? ''}
                  onChange={(e) => {
                    const next = [...inputs];
                    next[k] = e.target.value;
                    setInputs(next);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') handleGo();
                  }}
                  className="w-20 sm:w-24 h-11 text-center font-black text-xl text-[#1A1033] bg-white border-2 border-[#C5BFEE] focus:border-[#7C3AED] focus:ring-2 focus:ring-purple-200 rounded-2xl shadow-sm outline-none transition-all"
                />
              </label>
            ))}

            <button
              type="button"
              onClick={handleGo}
              className="h-11 px-5 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white font-black text-sm flex items-center gap-1.5 shadow-md shadow-emerald-500/25 hover:scale-105 active:scale-95 transition-all cursor-pointer self-end mb-0.5"
            >
              <span>✨</span>
              <span>Crear</span>
            </button>
          </div>

          {/* Whiteboard / Canvas Container */}
          <div
            ref={boardRef}
            className="w-full min-h-[320px] transition-all"
            dangerouslySetInnerHTML={{ __html: htmlContent }}
          />
        </div>
      </div>
    </div>
  );
}
